image:
  file: .gitpod.Dockerfile

experimentalNetwork: true

tasks:
  - name: tailscaled
    command: |
      sudo tailscaled
  - name: tailscale
    command: |
      sudo -E tailscale up --hostname "gitpod-${GITPOD_WORKSPACE_ID}" \
                           --authkey "${TAILSCALE_AUTHKEY}"
  - name: sshd
    command: |
      sudo ssh-keygen -A && sudo /usr/sbin/sshd

ports:
  - port: 22
    onOpen: ignore

